# properties for Lab 4
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:    
    metadataMap:      
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
server:  
  port: ${PORT:${SERVER_PORT:0}}
